package com.prej.familytree.relationship;

public enum RelationEnum {

	BROTHERS, BROTHERINLAW, CHILDREN, COUSINS, DAUGHTER, FATHER, GRANDDAUGHTER, MATERNALAUNT, MATERNALUNCLE, MOTHER, PATERNALAUNT, PATERNALUNCLE, SISTERINLAW, SISTERS, SON;

}
